import { NIGERIAN_BANKS } from './nigerianBanks';

export interface BankInstitution {
  name: string;
  code?: string;
  category?: string;
}

export interface CountryBankingProfile {
  countryCode: string;
  countryName: string;
  flagEmoji: string;
  currencyCode: string;
  currencySymbol: string;
  accountNumberLabel: string;
  accountNumberPlaceholder: string;
  routingCodeLabel: string;
  routingCodePlaceholder: string;
  accountNumberLength?: number;
  banks: BankInstitution[];
}

export const COUNTRIES_BANKING_PROFILES: CountryBankingProfile[] = [
  // --- AFRICA ---
  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    flagEmoji: '🇳🇬',
    currencyCode: 'NGN',
    currencySymbol: '₦',
    accountNumberLabel: 'NUBAN Account Number (10 Digits)',
    accountNumberPlaceholder: 'e.g. 0123456789',
    routingCodeLabel: 'Branch / Sort Code (Optional)',
    routingCodePlaceholder: 'Optional branch sort code',
    accountNumberLength: 10,
    banks: NIGERIAN_BANKS,
  },
  {
    countryCode: 'GH',
    countryName: 'Ghana',
    flagEmoji: '🇬🇭',
    currencyCode: 'GHS',
    currencySymbol: 'GH₵',
    accountNumberLabel: 'Account / MoMo Wallet Number',
    accountNumberPlaceholder: 'e.g. 0244123456 / 1002345678',
    routingCodeLabel: 'Branch / Sort Code (Optional)',
    routingCodePlaceholder: 'Optional branch code',
    banks: [
      { name: 'Absa Bank Ghana' },
      { name: 'Access Bank Ghana' },
      { name: 'Agricultural Development Bank (ADB)' },
      { name: 'Bank of Africa Ghana' },
      { name: 'CalBank' },
      { name: 'Consolidated Bank Ghana (CBG)' },
      { name: 'Ecobank Ghana' },
      { name: 'FBNBank Ghana' },
      { name: 'Fidelity Bank Ghana' },
      { name: 'First Atlantic Bank' },
      { name: 'First National Bank Ghana' },
      { name: 'GCB Bank' },
      { name: 'Guaranty Trust Bank Ghana' },
      { name: 'MTN Mobile Money (MoMo)' },
      { name: 'National Investment Bank' },
      { name: 'OmniBSIC Bank' },
      { name: 'Prudential Bank' },
      { name: 'Republic Bank Ghana' },
      { name: 'Societe Generale Ghana' },
      { name: 'Stanbic Bank Ghana' },
      { name: 'Standard Chartered Ghana' },
      { name: 'Telecel Cash (Vodafone)' },
      { name: 'Universal Merchant Bank (UMB)' },
      { name: 'Zenith Bank Ghana' },
    ],
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    flagEmoji: '🇰🇪',
    currencyCode: 'KES',
    currencySymbol: 'KSh',
    accountNumberLabel: 'Account / M-PESA Paybill / Till Number',
    accountNumberPlaceholder: 'e.g. 1100234567 / Paybill 522522',
    routingCodeLabel: 'Branch Code / Account Reference',
    routingCodePlaceholder: 'e.g. 01000',
    banks: [
      { name: 'Absa Bank Kenya' },
      { name: 'Bank of Africa Kenya' },
      { name: 'Citibank Kenya' },
      { name: 'Co-operative Bank of Kenya' },
      { name: 'Credit Bank' },
      { name: 'Diamond Trust Bank (DTB)' },
      { name: 'Equity Bank Kenya' },
      { name: 'Family Bank Kenya' },
      { name: 'Guaranty Trust Bank Kenya' },
      { name: 'Gulf African Bank' },
      { name: 'Habib Bank AG Zurich' },
      { name: 'I&M Bank Kenya' },
      { name: 'Kingdom Bank' },
      { name: 'KCB Bank Kenya' },
      { name: 'M-PESA (Safaricom Paybill/Till)' },
      { name: 'Middle East Bank' },
      { name: 'National Bank of Kenya' },
      { name: 'NCBA Bank Kenya' },
      { name: 'Paramount Bank' },
      { name: 'Prime Bank Kenya' },
      { name: 'Sidian Bank' },
      { name: 'Stanbic Bank Kenya' },
      { name: 'Standard Chartered Kenya' },
      { name: 'Victoria Commercial Bank' },
    ],
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    flagEmoji: '🇿🇦',
    currencyCode: 'ZAR',
    currencySymbol: 'R',
    accountNumberLabel: 'Account Number',
    accountNumberPlaceholder: 'e.g. 62012345678',
    routingCodeLabel: 'Branch Code (Universal 6 Digits)',
    routingCodePlaceholder: 'e.g. 250655',
    banks: [
      { name: 'ABSA Bank' },
      { name: 'African Bank' },
      { name: 'Bidvest Bank' },
      { name: 'Capitec Bank' },
      { name: 'Discovery Bank' },
      { name: 'First National Bank (FNB)' },
      { name: 'Grindrod Bank' },
      { name: 'Investec Bank' },
      { name: 'Mercantile Bank' },
      { name: 'Nedbank' },
      { name: 'Sasfin Bank' },
      { name: 'Standard Bank South Africa' },
      { name: 'TymeBank' },
      { name: 'Ubank' },
    ],
  },
  {
    countryCode: 'EG',
    countryName: 'Egypt',
    flagEmoji: '🇪🇬',
    currencyCode: 'EGP',
    currencySymbol: 'E£',
    accountNumberLabel: 'IBAN / Account Number',
    accountNumberPlaceholder: 'e.g. EG3800020001000000000123456',
    routingCodeLabel: 'SWIFT / BIC Code',
    routingCodePlaceholder: 'e.g. NBEGEGCX',
    banks: [
      { name: 'National Bank of Egypt (NBE)' },
      { name: 'Banque Misr' },
      { name: 'Commercial International Bank (CIB)' },
      { name: 'QNB Alahli' },
      { name: 'Banque du Caire' },
      { name: 'HSBC Egypt' },
      { name: 'AlexBank' },
      { name: 'Faisal Islamic Bank of Egypt' },
      { name: 'Arab African International Bank (AAIB)' },
      { name: 'Vodafone Cash / InstaPay' },
    ],
  },
  {
    countryCode: 'RW',
    countryName: 'Rwanda',
    flagEmoji: '🇷🇼',
    currencyCode: 'RWF',
    currencySymbol: 'FRw',
    accountNumberLabel: 'Account / MTN Mobile Money Number',
    accountNumberPlaceholder: 'e.g. 0788123456 / 40012345678',
    routingCodeLabel: 'Branch Code',
    routingCodePlaceholder: 'e.g. 0100',
    banks: [
      { name: 'Bank of Kigali (BK)' },
      { name: 'I&M Bank Rwanda' },
      { name: 'BPR Bank Rwanda (Part of Atlas Mara / KCB)' },
      { name: 'Equity Bank Rwanda' },
      { name: 'Cogebanque' },
      { name: 'Access Bank Rwanda' },
      { name: 'NCBA Bank Rwanda' },
      { name: 'MTN Mobile Money Rwanda' },
      { name: 'Airtel Money Rwanda' },
    ],
  },
  {
    countryCode: 'TZ',
    countryName: 'Tanzania',
    flagEmoji: '🇹🇿',
    currencyCode: 'TZS',
    currencySymbol: 'TSh',
    accountNumberLabel: 'Account Number / M-Pesa / Tigo Pesa',
    accountNumberPlaceholder: 'e.g. 01J1234567800',
    routingCodeLabel: 'Branch Code',
    routingCodePlaceholder: 'e.g. 01',
    banks: [
      { name: 'CRDB Bank' },
      { name: 'NMB Bank (National Microfinance Bank)' },
      { name: 'NBC (National Bank of Commerce)' },
      { name: 'Standard Chartered Tanzania' },
      { name: 'Stanbic Bank Tanzania' },
      { name: 'Absa Bank Tanzania' },
      { name: 'Exim Bank Tanzania' },
      { name: 'Vodacom M-Pesa' },
      { name: 'Tigo Pesa' },
    ],
  },
  {
    countryCode: 'UG',
    countryName: 'Uganda',
    flagEmoji: '🇺🇬',
    currencyCode: 'UGX',
    currencySymbol: 'USh',
    accountNumberLabel: 'Account Number / MTN MoMo',
    accountNumberPlaceholder: 'e.g. 0771234567 / 9030012345678',
    routingCodeLabel: 'Branch Code',
    routingCodePlaceholder: 'e.g. 01',
    banks: [
      { name: 'Stanbic Bank Uganda' },
      { name: 'Centenary Bank' },
      { name: 'Standard Chartered Uganda' },
      { name: 'Absa Bank Uganda' },
      { name: 'dfcu Bank' },
      { name: 'Equity Bank Uganda' },
      { name: 'Bank of Baroda Uganda' },
      { name: 'MTN Mobile Money Uganda' },
      { name: 'Airtel Money Uganda' },
    ],
  },

  // --- NORTH AMERICA ---
  {
    countryCode: 'US',
    countryName: 'United States',
    flagEmoji: '🇺🇸',
    currencyCode: 'USD',
    currencySymbol: '$',
    accountNumberLabel: 'Checking / Account Number',
    accountNumberPlaceholder: 'e.g. 123456789012',
    routingCodeLabel: 'ABA Routing Transit Number (9 Digits)',
    routingCodePlaceholder: 'e.g. 121000358',
    banks: [
      { name: 'Bank of America' },
      { name: 'Brex' },
      { name: 'Capital One' },
      { name: 'Charles Schwab' },
      { name: 'Citibank' },
      { name: 'Citizens Bank' },
      { name: 'Fifth Third Bank' },
      { name: 'First Citizens Bank' },
      { name: 'Goldman Sachs / Marcus' },
      { name: 'Huntington National Bank' },
      { name: 'JPMorgan Chase' },
      { name: 'KeyBank' },
      { name: 'M&T Bank' },
      { name: 'Mercury' },
      { name: 'Morgan Stanley' },
      { name: 'PNC Bank' },
      { name: 'Regions Bank' },
      { name: 'Relay Financial' },
      { name: 'Silicon Valley Bank (SVB)' },
      { name: 'TD Bank USA' },
      { name: 'Truist' },
      { name: 'U.S. Bank' },
      { name: 'USAA' },
      { name: 'Wells Fargo' },
      { name: 'Wise USA' },
      { name: 'Zelle Merchant' },
    ],
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    flagEmoji: '🇨🇦',
    currencyCode: 'CAD',
    currencySymbol: 'CA$',
    accountNumberLabel: 'Account Number (7 to 12 Digits)',
    accountNumberPlaceholder: 'e.g. 1234567',
    routingCodeLabel: 'Transit & Institution Number (e.g. 12345-001)',
    routingCodePlaceholder: 'e.g. 00001-003',
    banks: [
      { name: 'ATB Financial' },
      { name: 'BMO (Bank of Montreal)' },
      { name: 'CIBC' },
      { name: 'Desjardins' },
      { name: 'EQ Bank' },
      { name: 'HSBC Bank Canada' },
      { name: 'Laurentian Bank' },
      { name: 'National Bank of Canada' },
      { name: 'RBC Royal Bank' },
      { name: 'Scotiabank' },
      { name: 'Tangerine' },
      { name: 'TD Canada Trust' },
      { name: 'Vancity' },
    ],
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    flagEmoji: '🇲🇽',
    currencyCode: 'MXN',
    currencySymbol: 'MX$',
    accountNumberLabel: 'CLABE Interbancaria (18 Digits)',
    accountNumberPlaceholder: 'e.g. 012180001234567890',
    routingCodeLabel: 'Bank / Plaza Code',
    routingCodePlaceholder: 'e.g. 012',
    accountNumberLength: 18,
    banks: [
      { name: 'BBVA México' },
      { name: 'Santander México' },
      { name: 'Citibanamex' },
      { name: 'Banorte' },
      { name: 'HSBC México' },
      { name: 'Scotiabank México' },
      { name: 'Banco Azteca' },
      { name: 'Inbursa' },
      { name: 'Nu México' },
      { name: 'Hey Banco' },
    ],
  },

  // --- EUROPE & UK ---
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    flagEmoji: '🇬🇧',
    currencyCode: 'GBP',
    currencySymbol: '£',
    accountNumberLabel: 'Account Number (8 Digits)',
    accountNumberPlaceholder: 'e.g. 12345678',
    routingCodeLabel: 'Sort Code (6 Digits: XX-XX-XX)',
    routingCodePlaceholder: 'e.g. 20-00-00',
    accountNumberLength: 8,
    banks: [
      { name: 'Bank of Scotland' },
      { name: 'Barclays UK' },
      { name: 'Clydesdale Bank' },
      { name: 'Co-operative Bank' },
      { name: 'Coutts & Co' },
      { name: 'First Direct' },
      { name: 'Halifax' },
      { name: 'HSBC UK' },
      { name: 'Lloyds Bank' },
      { name: 'Metro Bank' },
      { name: 'Monzo' },
      { name: 'Nationwide Building Society' },
      { name: 'NatWest' },
      { name: 'Revolut UK' },
      { name: 'Royal Bank of Scotland (RBS)' },
      { name: 'Santander UK' },
      { name: 'Starling Bank' },
      { name: 'Tide' },
      { name: 'TSB Bank' },
      { name: 'Ulster Bank' },
      { name: 'Virgin Money' },
      { name: 'Wise UK' },
    ],
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    flagEmoji: '🇩🇪',
    currencyCode: 'EUR',
    currencySymbol: '€',
    accountNumberLabel: 'IBAN (e.g. DE89...)',
    accountNumberPlaceholder: 'e.g. DE89 3704 0044 0532 0130 00',
    routingCodeLabel: 'BIC / SWIFT Code',
    routingCodePlaceholder: 'e.g. DEUTDEDDXXX',
    banks: [
      { name: 'Deutsche Bank' },
      { name: 'Commerzbank' },
      { name: 'KfW Bankengruppe' },
      { name: 'DZ Bank' },
      { name: 'Sparkasse' },
      { name: 'Volksbanken Raiffeisenbanken' },
      { name: 'ING-DiBa Deutschland' },
      { name: 'N26' },
      { name: 'DKB (Deutsche Kreditbank)' },
      { name: 'Postbank' },
      { name: 'HypoVereinsbank (UniCredit)' },
      { name: 'Qonto Deutschland' },
    ],
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    flagEmoji: '🇫🇷',
    currencyCode: 'EUR',
    currencySymbol: '€',
    accountNumberLabel: 'IBAN (e.g. FR76...)',
    accountNumberPlaceholder: 'e.g. FR76 3000 6000 0112 3456 7890 189',
    routingCodeLabel: 'BIC / SWIFT Code',
    routingCodePlaceholder: 'e.g. BNPAFRPPXXX',
    banks: [
      { name: 'BNP Paribas' },
      { name: 'Crédit Agricole' },
      { name: 'Société Générale' },
      { name: 'BPCE (Banque Populaire / Caisse d’Épargne)' },
      { name: 'Crédit Mutuel' },
      { name: 'La Banque Postale' },
      { name: 'CIC' },
      { name: 'BoursoBank (Boursorama)' },
      { name: 'Qonto France' },
      { name: 'Shine' },
      { name: 'Revolut France' },
    ],
  },
  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    flagEmoji: '🇳🇱',
    currencyCode: 'EUR',
    currencySymbol: '€',
    accountNumberLabel: 'IBAN (e.g. NL91...)',
    accountNumberPlaceholder: 'e.g. NL91 ABNA 0417 1643 00',
    routingCodeLabel: 'BIC / SWIFT Code',
    routingCodePlaceholder: 'e.g. ABNANL2A',
    banks: [
      { name: 'ING Bank Netherlands' },
      { name: 'Rabobank' },
      { name: 'ABN AMRO' },
      { name: 'de Volksbank' },
      { name: 'Bunq' },
      { name: 'Triodos Bank' },
      { name: 'Knab' },
      { name: 'Revolut Netherlands' },
    ],
  },
  {
    countryCode: 'IE',
    countryName: 'Ireland',
    flagEmoji: '🇮🇪',
    currencyCode: 'EUR',
    currencySymbol: '€',
    accountNumberLabel: 'IBAN (e.g. IE29...)',
    accountNumberPlaceholder: 'e.g. IE29 AIBK 9311 5212 3456 78',
    routingCodeLabel: 'BIC / SWIFT Code',
    routingCodePlaceholder: 'e.g. AIBKIE2D',
    banks: [
      { name: 'AIB (Allied Irish Banks)' },
      { name: 'Bank of Ireland' },
      { name: 'Permanent TSB' },
      { name: 'EBS' },
      { name: 'Revolut Ireland' },
      { name: 'An Post Money' },
    ],
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    flagEmoji: '🇪🇸',
    currencyCode: 'EUR',
    currencySymbol: '€',
    accountNumberLabel: 'IBAN (e.g. ES91...)',
    accountNumberPlaceholder: 'e.g. ES91 2100 0418 4502 0005 1332',
    routingCodeLabel: 'BIC / SWIFT Code',
    routingCodePlaceholder: 'e.g. CAIXESBBXXX',
    banks: [
      { name: 'Banco Santander' },
      { name: 'BBVA España' },
      { name: 'CaixaBank' },
      { name: 'Banco Sabadell' },
      { name: 'Bankinter' },
      { name: 'Unicaja Banco' },
      { name: 'Abanca' },
      { name: 'Openbank' },
      { name: 'ING España' },
    ],
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    flagEmoji: '🇮🇹',
    currencyCode: 'EUR',
    currencySymbol: '€',
    accountNumberLabel: 'IBAN (e.g. IT60...)',
    accountNumberPlaceholder: 'e.g. IT60 X054 2811 1010 0000 0123 456',
    routingCodeLabel: 'BIC / SWIFT Code',
    routingCodePlaceholder: 'e.g. UNCRITM1XXX',
    banks: [
      { name: 'Intesa Sanpaolo' },
      { name: 'UniCredit' },
      { name: 'Banco BPM' },
      { name: 'BPER Banca' },
      { name: 'Banca Monte dei Paschi di Siena (MPS)' },
      { name: 'Poste Italiane (Postepay)' },
      { name: 'FinecoBank' },
      { name: 'Illimity Bank' },
    ],
  },
  {
    countryCode: 'CH',
    countryName: 'Switzerland',
    flagEmoji: '🇨🇭',
    currencyCode: 'CHF',
    currencySymbol: 'CHF',
    accountNumberLabel: 'Swiss IBAN (e.g. CH93...)',
    accountNumberPlaceholder: 'e.g. CH93 0076 2011 6238 5295 7',
    routingCodeLabel: 'BIC / SWIFT / Clearing Code',
    routingCodePlaceholder: 'e.g. UBSWCHZHXXX',
    banks: [
      { name: 'UBS Switzerland' },
      { name: 'Credit Suisse (UBS)' },
      { name: 'Raiffeisen Switzerland' },
      { name: 'Zürcher Kantonalbank (ZKB)' },
      { name: 'PostFinance' },
      { name: 'Julius Bär' },
      { name: 'Banque Cantonale de Genève (BCGE)' },
      { name: 'Neon Switzerland' },
      { name: 'Yuh' },
    ],
  },
  {
    countryCode: 'EU',
    countryName: 'European Union (General SEPA)',
    flagEmoji: '🇪🇺',
    currencyCode: 'EUR',
    currencySymbol: '€',
    accountNumberLabel: 'International Bank Account Number (IBAN)',
    accountNumberPlaceholder: 'e.g. DE89 / FR76 / NL91 / ES91 ...',
    routingCodeLabel: 'SWIFT / BIC Code',
    routingCodePlaceholder: 'e.g. DEUTDEDDXXX',
    banks: [
      { name: 'BNP Paribas Eurozone' },
      { name: 'Bunq' },
      { name: 'Crédit Agricole' },
      { name: 'Deutsche Bank' },
      { name: 'Erste Group' },
      { name: 'ING Group' },
      { name: 'Intesa Sanpaolo' },
      { name: 'KBC Bank' },
      { name: 'N26' },
      { name: 'Nordea' },
      { name: 'Qonto' },
      { name: 'Rabobank' },
      { name: 'Revolut EU' },
      { name: 'Santander Eurozone' },
      { name: 'Société Générale' },
      { name: 'UBS Europe' },
    ],
  },

  // --- MIDDLE EAST & ASIA-PACIFIC ---
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates (UAE)',
    flagEmoji: '🇦🇪',
    currencyCode: 'AED',
    currencySymbol: 'AED',
    accountNumberLabel: 'UAE IBAN (23 Characters: AE...)',
    accountNumberPlaceholder: 'e.g. AE07 0331 2345 6789 0123 456',
    routingCodeLabel: 'SWIFT / BIC Code',
    routingCodePlaceholder: 'e.g. ENBDADAAXXX',
    banks: [
      { name: 'First Abu Dhabi Bank (FAB)' },
      { name: 'Emirates NBD' },
      { name: 'Abu Dhabi Commercial Bank (ADCB)' },
      { name: 'Dubai Islamic Bank (DIB)' },
      { name: 'Mashreq Bank' },
      { name: 'Abu Dhabi Islamic Bank (ADIB)' },
      { name: 'Commercial Bank of Dubai (CBD)' },
      { name: 'RAKBANK' },
      { name: 'Wio Bank' },
      { name: 'Liv. by Emirates NBD' },
    ],
  },
  {
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    flagEmoji: '🇸🇦',
    currencyCode: 'SAR',
    currencySymbol: 'SAR',
    accountNumberLabel: 'Saudi IBAN (24 Characters: SA...)',
    accountNumberPlaceholder: 'e.g. SA03 8000 0000 6080 1016 7519',
    routingCodeLabel: 'SWIFT / BIC Code',
    routingCodePlaceholder: 'e.g. NCBKSAJE',
    banks: [
      { name: 'Saudi National Bank (SNB / AlAhli)' },
      { name: 'Al Rajhi Bank' },
      { name: 'Riyad Bank' },
      { name: 'Banque Saudi Fransi' },
      { name: 'Arab National Bank (ANB)' },
      { name: 'Alinma Bank' },
      { name: 'Saudi Awwal Bank (SAB)' },
      { name: 'Bank AlJazira' },
      { name: 'STC Pay / Urpay' },
    ],
  },
  {
    countryCode: 'IN',
    countryName: 'India',
    flagEmoji: '🇮🇳',
    currencyCode: 'INR',
    currencySymbol: '₹',
    accountNumberLabel: 'Bank Account Number / UPI ID',
    accountNumberPlaceholder: 'e.g. 123456789012 / user@okaxis',
    routingCodeLabel: 'IFSC Code (11 Characters)',
    routingCodePlaceholder: 'e.g. HDFC0001234 / SBIN0005678',
    banks: [
      { name: 'State Bank of India (SBI)' },
      { name: 'HDFC Bank' },
      { name: 'ICICI Bank' },
      { name: 'Axis Bank' },
      { name: 'Kotak Mahindra Bank' },
      { name: 'Punjab National Bank (PNB)' },
      { name: 'Bank of Baroda' },
      { name: 'IndusInd Bank' },
      { name: 'Yes Bank' },
      { name: 'IDFC FIRST Bank' },
      { name: 'UPI / PhonePe / GPay Merchant' },
    ],
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    flagEmoji: '🇸🇬',
    currencyCode: 'SGD',
    currencySymbol: 'S$',
    accountNumberLabel: 'Account Number / PayNow UEN/Mobile',
    accountNumberPlaceholder: 'e.g. 123-456789-0 / UEN 202112345A',
    routingCodeLabel: 'Bank Code & Branch Code',
    routingCodePlaceholder: 'e.g. 7171-001 (DBS)',
    banks: [
      { name: 'DBS Bank / POSB' },
      { name: 'OCBC Bank' },
      { name: 'United Overseas Bank (UOB)' },
      { name: 'Standard Chartered Singapore' },
      { name: 'Citibank Singapore' },
      { name: 'HSBC Singapore' },
      { name: 'Maybank Singapore' },
      { name: 'Aspire Business' },
      { name: 'GrabPay / PayNow' },
    ],
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    flagEmoji: '🇦🇺',
    currencyCode: 'AUD',
    currencySymbol: 'A$',
    accountNumberLabel: 'Account Number (6 to 9 Digits)',
    accountNumberPlaceholder: 'e.g. 12345678',
    routingCodeLabel: 'BSB Number (6 Digits: XXX-XXX)',
    routingCodePlaceholder: 'e.g. 062-000',
    banks: [
      { name: 'Commonwealth Bank of Australia (CBA)' },
      { name: 'Westpac' },
      { name: 'National Australia Bank (NAB)' },
      { name: 'ANZ (Australia and New Zealand Banking Group)' },
      { name: 'Macquarie Bank' },
      { name: 'Bendigo and Adelaide Bank' },
      { name: 'Bank of Queensland (BOQ)' },
      { name: 'Suncorp Bank' },
      { name: 'Up Bank' },
      { name: 'ING Australia' },
    ],
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    flagEmoji: '🇳🇿',
    currencyCode: 'NZD',
    currencySymbol: 'NZ$',
    accountNumberLabel: 'Account Number (15-16 Digits: XX-XXXX-XXXXXXX-XX)',
    accountNumberPlaceholder: 'e.g. 01-0123-0123456-00',
    routingCodeLabel: 'Bank & Branch Code',
    routingCodePlaceholder: 'e.g. 01-0123',
    banks: [
      { name: 'ANZ Bank New Zealand' },
      { name: 'ASB Bank' },
      { name: 'Bank of New Zealand (BNZ)' },
      { name: 'Westpac New Zealand' },
      { name: 'Kiwibank' },
      { name: 'TSB Bank New Zealand' },
      { name: 'Heartland Bank' },
    ],
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    flagEmoji: '🇧🇷',
    currencyCode: 'BRL',
    currencySymbol: 'R$',
    accountNumberLabel: 'Conta Corrente / Chave PIX',
    accountNumberPlaceholder: 'e.g. 12345-6 / Chave PIX (CPF/CNPJ/Email)',
    routingCodeLabel: 'Agência (4 Digits) + Código Banco',
    routingCodePlaceholder: 'e.g. 0001 (Itaú 341)',
    banks: [
      { name: 'Itaú Unibanco' },
      { name: 'Banco do Brasil' },
      { name: 'Bradesco' },
      { name: 'Caixa Econômica Federal' },
      { name: 'Santander Brasil' },
      { name: 'Nubank' },
      { name: 'Banco Inter' },
      { name: 'C6 Bank' },
      { name: 'BTG Pactual' },
      { name: 'PIX Settlement' },
    ],
  },

  // --- GLOBAL WIRE / OTHER ---
  {
    countryCode: 'GLOBAL',
    countryName: 'International / Other Countries (Global Wire)',
    flagEmoji: '🌍',
    currencyCode: 'USD',
    currencySymbol: '$',
    accountNumberLabel: 'Account Number / International IBAN',
    accountNumberPlaceholder: 'Account number or IBAN string',
    routingCodeLabel: 'SWIFT / BIC / Clearing Code',
    routingCodePlaceholder: 'e.g. CHASUS33XXX',
    banks: [
      { name: 'Direct Commercial Bank Wire' },
      { name: 'Wise Business (TransferWise)' },
      { name: 'Payoneer Merchant Account' },
      { name: 'Revolut Business Multi-Currency' },
      { name: 'Stripe Settlement Payout Account' },
      { name: 'PayPal Merchant Account' },
      { name: 'Airwallex' },
    ],
  },
];

export function getCountryProfile(countryCode: string = 'NG'): CountryBankingProfile {
  const match = COUNTRIES_BANKING_PROFILES.find(
    (c) => c.countryCode.toUpperCase() === countryCode.toUpperCase()
  );
  return match || COUNTRIES_BANKING_PROFILES[0];
}
