import { NIGERIAN_BANKS } from './nigerianBanks';

export interface BankInstitution {
  name: string;
  code?: string;
  category?: string;
}

export interface CountryBankingProfile {
  countryCode: string;
  countryName: string;
  flagEmoji: string;
  currencyCode: string;
  currencySymbol: string;
  accountNumberLabel: string;
  accountNumberPlaceholder: string;
  routingCodeLabel: string;
  routingCodePlaceholder: string;
  accountNumberLength?: number;
  banks: BankInstitution[];
}

export const COUNTRIES_BANKING_PROFILES: CountryBankingProfile[] = [
  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    flagEmoji: '🇳🇬',
    currencyCode: 'NGN',
    currencySymbol: '₦',
    accountNumberLabel: 'NUBAN Account Number (10 Digits)',
    accountNumberPlaceholder: 'e.g. 0123456789',
    routingCodeLabel: 'Branch / Sort Code (Optional)',
    routingCodePlaceholder: 'Optional branch sort code',
    accountNumberLength: 10,
    banks: NIGERIAN_BANKS,
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    flagEmoji: '🇺🇸',
    currencyCode: 'USD',
    currencySymbol: '$',
    accountNumberLabel: 'Checking / Account Number',
    accountNumberPlaceholder: 'e.g. 123456789012',
    routingCodeLabel: 'ABA Routing Transit Number (9 Digits)',
    routingCodePlaceholder: 'e.g. 121000358',
    banks: [
      { name: 'Bank of America' },
      { name: 'Brex' },
      { name: 'Capital One' },
      { name: 'Charles Schwab' },
      { name: 'Citibank' },
      { name: 'Goldman Sachs / Marcus' },
      { name: 'JPMorgan Chase' },
      { name: 'M&T Bank' },
      { name: 'Mercury' },
      { name: 'PNC Bank' },
      { name: 'Relay Financial' },
      { name: 'Silicon Valley Bank (SVB)' },
      { name: 'TD Bank USA' },
      { name: 'Truist' },
      { name: 'U.S. Bank' },
      { name: 'Wells Fargo' },
      { name: 'Other US Commercial Bank' },
    ],
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    flagEmoji: '🇬🇧',
    currencyCode: 'GBP',
    currencySymbol: '£',
    accountNumberLabel: 'Account Number (8 Digits)',
    accountNumberPlaceholder: 'e.g. 12345678',
    routingCodeLabel: 'Sort Code (6 Digits: XX-XX-XX)',
    routingCodePlaceholder: 'e.g. 20-00-00',
    accountNumberLength: 8,
    banks: [
      { name: 'Barclays UK' },
      { name: 'Clydesdale Bank' },
      { name: 'Co-operative Bank' },
      { name: 'HSBC UK' },
      { name: 'Lloyds Bank' },
      { name: 'Metro Bank' },
      { name: 'Monzo' },
      { name: 'Nationwide Building Society' },
      { name: 'NatWest' },
      { name: 'Revolut UK' },
      { name: 'Royal Bank of Scotland (RBS)' },
      { name: 'Santander UK' },
      { name: 'Starling Bank' },
      { name: 'TSB Bank' },
      { name: 'Virgin Money' },
      { name: 'Other UK Bank' },
    ],
  },
  {
    countryCode: 'EU',
    countryName: 'European Union (SEPA / Eurozone)',
    flagEmoji: '🇪🇺',
    currencyCode: 'EUR',
    currencySymbol: '€',
    accountNumberLabel: 'International Bank Account Number (IBAN)',
    accountNumberPlaceholder: 'e.g. DE89 3704 0044 0532 0130 00',
    routingCodeLabel: 'SWIFT / BIC Code',
    routingCodePlaceholder: 'e.g. DEUTDEDDXXX',
    banks: [
      { name: 'BNP Paribas' },
      { name: 'Bunq' },
      { name: 'Crédit Agricole' },
      { name: 'Deutsche Bank' },
      { name: 'Erste Group' },
      { name: 'ING Group' },
      { name: 'Intesa Sanpaolo' },
      { name: 'KBC Bank' },
      { name: 'N26' },
      { name: 'Nordea' },
      { name: 'Qonto' },
      { name: 'Rabobank' },
      { name: 'Revolut EU' },
      { name: 'Santander Eurozone' },
      { name: 'Société Générale' },
      { name: 'UBS Europe' },
      { name: 'Other European Bank' },
    ],
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    flagEmoji: '🇨🇦',
    currencyCode: 'CAD',
    currencySymbol: 'CA$',
    accountNumberLabel: 'Account Number (7 to 12 Digits)',
    accountNumberPlaceholder: 'e.g. 1234567',
    routingCodeLabel: 'Transit & Institution Number (e.g. 12345-001)',
    routingCodePlaceholder: 'e.g. 00001-003',
    banks: [
      { name: 'BMO (Bank of Montreal)' },
      { name: 'CIBC' },
      { name: 'Desjardins' },
      { name: 'EQ Bank' },
      { name: 'National Bank of Canada' },
      { name: 'RBC Royal Bank' },
      { name: 'Scotiabank' },
      { name: 'Tangerine' },
      { name: 'TD Canada Trust' },
      { name: 'Other Canadian Bank' },
    ],
  },
  {
    countryCode: 'GH',
    countryName: 'Ghana',
    flagEmoji: '🇬🇭',
    currencyCode: 'GHS',
    currencySymbol: 'GH₵',
    accountNumberLabel: 'Account / MoMo Wallet Number',
    accountNumberPlaceholder: 'e.g. 0244123456 / 1002345678',
    routingCodeLabel: 'Branch / Sort Code (Optional)',
    routingCodePlaceholder: 'Optional branch code',
    banks: [
      { name: 'Absa Bank Ghana' },
      { name: 'Access Bank Ghana' },
      { name: 'CalBank' },
      { name: 'Ecobank Ghana' },
      { name: 'FBNBank Ghana' },
      { name: 'Fidelity Bank Ghana' },
      { name: 'GCB Bank' },
      { name: 'Guaranty Trust Bank Ghana' },
      { name: 'MTN Mobile Money (MoMo)' },
      { name: 'Prudential Bank' },
      { name: 'Stanbic Bank Ghana' },
      { name: 'Standard Chartered Ghana' },
      { name: 'Telecel Cash (Vodafone)' },
      { name: 'Zenith Bank Ghana' },
      { name: 'Other Ghana Bank' },
    ],
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    flagEmoji: '🇰🇪',
    currencyCode: 'KES',
    currencySymbol: 'KSh',
    accountNumberLabel: 'Account / M-PESA Paybill / Till Number',
    accountNumberPlaceholder: 'e.g. 1100234567 / Paybill 522522',
    routingCodeLabel: 'Branch Code / Account Reference',
    routingCodePlaceholder: 'e.g. 01000',
    banks: [
      { name: 'Absa Bank Kenya' },
      { name: 'Co-operative Bank of Kenya' },
      { name: 'Diamond Trust Bank (DTB)' },
      { name: 'Equity Bank Kenya' },
      { name: 'I&M Bank' },
      { name: 'KCB Bank Kenya' },
      { name: 'M-PESA (Safaricom Paybill/Till)' },
      { name: 'NCBA Bank Kenya' },
      { name: 'Stanbic Bank Kenya' },
      { name: 'Standard Chartered Kenya' },
      { name: 'Other Kenya Bank' },
    ],
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    flagEmoji: '🇿🇦',
    currencyCode: 'ZAR',
    currencySymbol: 'R',
    accountNumberLabel: 'Account Number',
    accountNumberPlaceholder: 'e.g. 62012345678',
    routingCodeLabel: 'Branch Code (Universal 6 Digits)',
    routingCodePlaceholder: 'e.g. 250655',
    banks: [
      { name: 'ABSA Bank' },
      { name: 'Capitec Bank' },
      { name: 'Discovery Bank' },
      { name: 'First National Bank (FNB)' },
      { name: 'Investec' },
      { name: 'Nedbank' },
      { name: 'Standard Bank South Africa' },
      { name: 'TymeBank' },
      { name: 'Other South African Bank' },
    ],
  },
  {
    countryCode: 'GLOBAL',
    countryName: 'International / Other Countries',
    flagEmoji: '🌍',
    currencyCode: 'USD',
    currencySymbol: '$',
    accountNumberLabel: 'Account Number / IBAN',
    accountNumberPlaceholder: 'Account or IBAN code',
    routingCodeLabel: 'SWIFT / BIC / Wire Routing Code',
    routingCodePlaceholder: 'SWIFT / BIC code',
    banks: [
      { name: 'Direct Commercial Bank Wire' },
      { name: 'Wise (TransferWise)' },
      { name: 'Payoneer' },
      { name: 'Revolut Business' },
      { name: 'PayPal Merchant' },
      { name: 'Stripe Settlement Account' },
      { name: 'Other International Bank' },
    ],
  },
];

export function getCountryProfile(countryCode: string = 'NG'): CountryBankingProfile {
  const match = COUNTRIES_BANKING_PROFILES.find(
    (c) => c.countryCode.toUpperCase() === countryCode.toUpperCase()
  );
  return match || COUNTRIES_BANKING_PROFILES[0];
}
